version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  postgresql:
    image: postgres

  movieapi:
    image: ${DOCKER_REGISTRY-}movieapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/services/movie.api/Dockerfile
    depends_on:
      - postgresql

  movieweb:
    image: ${DOCKER_REGISTRY-}movieweb:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/movie.web/Dockerfile

  moviestatus:
    image: ${DOCKER_REGISTRY-}moviestatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/movie.status/Dockerfile