version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  postgresql:
    image: postgres

  movie.api:
    image: ${DOCKER_REGISTRY-}movieapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/services/movie.api/Dockerfile
    depends_on:
      - postgresql

  movie.web:
    image: ${DOCKER_REGISTRY-}movieweb:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/movie.web/Dockerfile