version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
      - TZ=Asia/Jakarta
    ports:
      - "5340:80"

  movie.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Jakarta
    ports:
      - "3001:80"

  movie.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Jakarta
    ports:
      - "3000:80"
