version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
      - TZ=Asia/Jakarta
    ports:
      - "5340:80"

  postgresql:
    environment:
      - POSTGRES_PASSWORD=1q2w3e4r
      - TZ=Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

  movieapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Host=postgresql;User ID=postgres;Password=1q2w3e4r;Database=movie;Pooling=true;
      - PATH_BASE=/movie-api
      - TZ=Asia/Jakarta
    ports:
      - "5210:80"

  movieweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Asia/Jakarta
    ports:
      - "5211:80"

  moviestatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Movie Web HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://movieweb/hc
      - HealthChecksUI__HealthChecks__1__Name=Movie API HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://movieapi/hc
      - TZ=Asia/Jakarta
    ports:
      - "5212:80"

volumes:
  postgresql:
    external: false
